name: Build & Push images

on:
  push:
    tags:
      - "*.*.*"   # Matches tags like 1.0.0, 2.1.3, etc.
  workflow_dispatch:

env:
  IMAGE_NAME: mrcolorrain/jnp

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine Tag Name
        id: vars
        run: echo "VERSION_TAG=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Build & Push Base image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./base.dockerfile
          platforms: linux/amd64
          push: true
          # This pushes two tags: "base" and also "base-<version>"
          tags: |
            ${{ env.IMAGE_NAME }}:base
            ${{ env.IMAGE_NAME }}:base-${{ steps.vars.outputs.VERSION_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & Push Coder image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./coder.dockerfile
          platforms: linux/amd64
          push: true
          # This pushes two tags: "coder" and also "coder-<version>"
          tags: |
            ${{ env.IMAGE_NAME }}:coder
            ${{ env.IMAGE_NAME }}:coder-${{ steps.vars.outputs.VERSION_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
